---
title: "R for MSF rest report"
author: "Didac Fortuny"
date: "22/6/2019"
output: pdf_document
---

```{r LIBRARIES, include=FALSE}
library(dplyr)
library(knitr)
library(readxl)
```

```{r READ DATA, include=FALSE}
pss_data <- read_excel("data/PSS-Sample DataSet no password.xlsx")
```

```{r SEPARATE DATA BY ROUND, include=FALSE}
pss_data_round_1 <- pss_data %>% filter(Round == 1)
pss_data_round_2 <- pss_data %>% filter(Round == 2)
```

# How happy are you with the staff (nurses and doctors) working in the facility?

## Round 1

```{r How happy are you with the staff (nurses and doctors) working in the facility?, echo=FALSE, results="asis"}
data <- pss_data_round_1

data <- data %>% select(happiness = How_happy_are_you_with_the_staff_working_in_the_facility)

data_satisfaction <- data

data_satisfaction$happiness <- as.factor(data_satisfaction$happiness)

data_satisfaction$happiness <- ordered(data_satisfaction$happiness, c("very_happy", "happy", "neutral", "unhappy", "very_unhappy"))

summary_table <- data_satisfaction %>% group_by(happiness) %>% summarise(N = n())
summary_table <- summary_table %>% arrange(happiness)
summary_table <- summary_table %>% mutate(Percentage = 100 * N / sum(N))
summary_table$Cumulative_percentage <- cumsum(summary_table$Percentage)

kable(summary_table, caption = "How happy are you with the staff (nurses and doctors) working in the facility?")
```

```{r Number of happy or very happy, echo=FALSE}
happy <- data %>% filter(happiness %in% c("happy", "very_happy"))
happy <- nrow(happy)
```

The number of patients who were Very happy or Happy with the staff was `r happy`.


## Round 2

(Remember to change the name of the chunks when copying parts of code!)

```{r How happy are you with the staff (nurses and doctors) working in the facility? ROUND 2, echo=FALSE, results="asis"}
data <- pss_data_round_2

data <- data %>% select(happiness = How_happy_are_you_with_the_staff_working_in_the_facility)

data_satisfaction <- data

data_satisfaction$happiness <- as.factor(data_satisfaction$happiness)

data_satisfaction$happiness <- ordered(data_satisfaction$happiness, c("very_happy", "happy", "neutral", "unhappy", "very_unhappy"))

summary_table <- data_satisfaction %>% group_by(happiness) %>% summarise(N = n())
summary_table <- summary_table %>% arrange(happiness)
summary_table <- summary_table %>% mutate(Percentage = 100 * N / sum(N))
summary_table$Cumulative_percentage <- cumsum(summary_table$Percentage)

kable(summary_table, caption = "How happy are you with the staff (nurses and doctors) working in the facility?")
```

```{r Number of happy or very happy ROUND 2, echo=FALSE}
happy <- data %>% filter(happiness %in% c("happy", "very_happy"))
happy <- nrow(happy)
```

The number of patients who were Very happy or Happy with the staff was `r happy`.

# DEMOGRAPHICS

```{r DEMOGRAPHIC STATISTICS, echo=FALSE}
data_demo <- pss_data %>% select(age_years, gender, language)
data_demo$age_group <- NA
data_demo$age_group[data_demo$age_years <= 15] <- "under 16"
data_demo$age_group[data_demo$age_years > 50] <- "over 50"
data_demo$age_group[(data_demo$age_years > 15) & (data_demo$age_years <= 50)] <- "in the middle"

gender_demo <- data_demo %>% group_by(gender) %>%
    summarize(number_of_records = n()) %>%
    mutate(Percentage = 100 * number_of_records / sum(number_of_records))

kable(gender_demo, caption = "Gender demographics")

age_demo <- data_demo %>% group_by(age_group) %>%
    summarize(number_of_records = n()) %>%
    mutate(Percentage = 100 * number_of_records / sum(number_of_records))

kable(age_demo, caption = "Age demographics")

language_demo <- data_demo %>% group_by(language) %>%
    summarize(number_of_records = n()) %>%
    mutate(Percentage = 100 * number_of_records / sum(number_of_records))

kable(language_demo, caption = "Language demographics")

```

